### ISSUE TITLE
OnItemClickListener dispatch event for both listView

### ISSUE THREAD

**Issue by gafrancischini** [vladexologija/PinterestListView#2]
the OnItemClickListener is dispatching the click event for both listviews( left and right).

This is a weird issue as only one of the listview should dispatch the click event.

How to solve this issue?

Thanks

**Comment by vladexologija** [comment]
The synchronization works so that both touch and scroll actions from one list are passed to another. That's how I forced them to work together. The drawback is that "clicks" are also passed. A temporary solution (until I figure out something better) is to add some sort of side variable in onTouch listener and later see which side was clicked.
